import type { Metadata } from 'next';
import './globals.css';
import SiteFooter from '@/components/front-end/site-footer';
import SiteHeader from '@/components/front-end/site-header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={``}>
        <SiteHeader />
        {children}
        <SiteFooter />
      </body>
    </html>
  );
}
